%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\Users\Tom K\Google Drive\Programs\courses\Computing\main\matlab\SatelliteDatabase.txt
%
% Auto-generated by MATLAB on 28-Sep-2020 12:52:29

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 8);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = " ";

% Specify column names and types
opts.VariableNames = ["Name", "Country", "Purpose", "Altitude", "Period", "Mass", "Year", "Lifetime"];
opts.VariableTypes = ["string", "string", "string", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";
opts.ConsecutiveDelimitersRule = "join";
opts.LeadingDelimitersRule = "ignore";

% Specify variable properties
opts = setvaropts(opts, ["Name", "Country", "Purpose"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Name", "Country", "Purpose"], "EmptyFieldRule", "auto");

% Import the data
Sdata = readtable("C:\Users\Tom K\Google Drive\Programs\courses\Computing\main\matlab\SatelliteDatabase.txt", opts);


%% Clear temporary variables
clear opts

Sdata.Period



